#!/bin/bash

# Error Boundary Test Script
# This script helps you manually test the error boundary in the Next.js app

echo "========================================="
echo "Error Boundary Testing Script"
echo "========================================="
echo ""
echo "This script will help you test the error boundary manually."
echo ""
echo "To test the error boundary, follow these steps:"
echo ""
echo "1. Start the development server:"
echo "   npm run dev (or bun dev if you have bun installed)"
echo ""
echo "2. Test Main Page Error:"
echo "   - Add this line at the top of src/app/[lang]/page.tsx:"
echo "     throw new Error('Test error on main page');"
echo "   - Visit http://localhost:3000/en"
echo "   - You should see the error UI with 'Try again' button"
echo "   - Click 'Try again' to verify reset functionality"
echo "   - Remove the test error when done"
echo ""
echo "3. Test Country Detail Page Error:"
echo "   - Add this line at the top of src/app/[lang]/country/[id]/page.tsx:"
echo "     throw new Error('Test error on country page');"
echo "   - Visit http://localhost:3000/en/country/USA"
echo "   - You should see the error UI"
echo "   - Verify the error is caught by the parent error boundary"
echo "   - Remove the test error when done"
echo ""
echo "4. Test API Error:"
echo "   - Edit src/api/getCountries.ts"
echo "   - Make it throw an error instead of fetching data"
echo "   - Refresh the page to see the error boundary"
echo "   - Restore the original code when done"
echo ""
echo "5. Check Console Logs:"
echo "   - Open browser DevTools (F12)"
echo "   - Check the Console tab for error logs"
echo "   - The error should be logged with the prefix:"
echo "     'Error caught by error boundary:'"
echo ""
echo "========================================="
echo "Key Points:"
echo "========================================="
echo ""
echo "✓ Only ONE error.tsx file is needed at src/app/[lang]/error.tsx"
echo "✓ It catches errors from all child routes including /country/[id]"
echo "✓ Having both /[lang]/error.tsx AND /[lang]/country/[id]/error.tsx"
echo "  would be REDUNDANT unless you need different error UIs"
echo ""
echo "✓ error.tsx catches runtime errors (thrown errors, failed promises)"
echo "✓ not-found.tsx handles 404 cases (when notFound() is called)"
echo ""
echo "========================================="
